# Generated by Django 4.2.3 on 2023-08-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0004_alter_onlineshop_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineshop',
            name='imag',
            field=models.ImageField(default=1, upload_to='online_shop/static/img/', verbose_name='Изображени'),
            preserve_default=False,
        ),
    ]
